development:
  adapter: postgresql
  database: orm_marketplace_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: orm_marketplace_test
  pool: 5
  timeout: 5000
  host: localhost
